#ifndef SH_MATH_BASIC_MATH_INCLUDES_HPP
#define SH_MATH_BASIC_MATH_INCLUDES_HPP

#include <cinttypes>

#ifdef  USE_STANDART_MATH
#include <cmath>
#endif//USE_STANDART_MATH

#endif//SH_MATH_BASIC_MATH_INCLUDES_HPP